### ISSUE TITLE
Intro Screen

### ISSUE THREAD

**Issue by BkrTech101-InnovaMind** [BkrTech101-InnovaMind/tadllal-app#1]
# Title:
Designing the Intro Screen component

## Description:
Build the UI for the Intro Screen that is just like the image below.

## Subtasks
- [ ] Implement a Onboarding screen
- [ ] Implement a tour-1 screen
- [ ] Implement a tour-2 screen
- [ ] Implement a tour-3 screen 

## Screenshots:
![image](https://github.com/BkrTech101-InnovaMind/tadllal-app/assets/93738112/afb92f55-58fe-4536-866f-8b84e61428c6)

**Link to the component on Figma**
[Here](https://www.figma.com/file/nm09ZFAgAyTGnW8cvoiiW3/tadllal?type=design&node-id=17-38&mode=design&t=7alhn1SyvzSzj5nK-4)
