### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by BkrTech101-InnovaMind** [BkrTech101-InnovaMind/tadllal-app#2]
# Title:
Designing the home page component

## Description:
Build the UI for the Home Page that is just like the image below.

## Subtasks
- [ ] Implement services zone 
- [ ] Implement more requested zone with it's options filter
- [ ] Implement best locations zone with it's options filter
- [ ] Implement descover real estate zone with it's options filter
- [ ] Implement real estates list with the needed UI

## Screenshots:
![image](https://github.com/BkrTech101-InnovaMind/tadllal-app/assets/93738112/d54b698e-27a8-4cef-8344-8ad1e421a1c4)

**Link to the component on Figma**
[Here](https://www.figma.com/file/nm09ZFAgAyTGnW8cvoiiW3/tadllal?type=design&node-id=136-472&mode=design&t=7alhn1SyvzSzj5nK-4)
