### ISSUE TITLE
Button Navigation Bar

### ISSUE THREAD

**Issue by BkrTech101-InnovaMind** [BkrTech101-InnovaMind/tadllal-app#3]
# Title:
Designing the Button Navigation Bar component

## Description:
Build the UI for the Button Navigation Bar that is just like the image below.

## Subtasks
- [x] Implement Home Page routing
- [x] Implement Search page routing
- [x] Implement Favorited page routing
- [x] Implement User Page routing

## Screenshots:
![image](https://github.com/BkrTech101-InnovaMind/tadllal-app/assets/93738112/b5b4b636-c072-4382-9252-7d9408daadc7)

**Link to the component on Figma**
[Here](https://www.figma.com/file/nm09ZFAgAyTGnW8cvoiiW3/tadllal?type=design&node-id=136-568&mode=design&t=7alhn1SyvzSzj5nK-4)
